import type { Character } from './types';

export const CHARACTERS: Record<string, Character> = {
  raindrop: {
    id: 'raindrop',
    name: '雨滴',
    emoji: '🌧️',
    title: '眼淚收藏員',
    location: '雨之湖',
    emotionsFocused: ['悲傷', '委屈', '失落', '離別'],
    dailyTask: '把眼淚變成露珠，澆灌小參室裡的植物',
    pastVulnerability: '雨滴也曾經不敢哭。是長老告訴她，眼淚是心在呼吸。',
    companionMessage: '雨滴什麼都沒說，只是遞給你一條乾毛巾。她今天也把你的眼淚收進玻璃瓶了。',
  },
  mist: {
    id: 'mist',
    name: '霧霧',
    emoji: '🌫️',
    title: '迷途引路人',
    location: '迷霧谷',
    emotionsFocused: ['迷惘', '選擇', '不知道怎麼辦'],
    dailyTask: '背著羅盤陪別人走，不是帶路，而是陪別人走',
    pastVulnerability: '霧霧曾經也很急著看清楚前路。現在他知道，路不一定要現在就看清楚。',
    companionMessage: '霧霧笑笑地說：「慢慢來。」他背著羅盤，準備陪你走一段路。',
  },
  thunder: {
    id: 'thunder',
    name: '雷雷',
    emoji: '⚡',
    title: '界線守護者',
    location: '雷鳴山',
    emotionsFocused: ['憤怒', '害怕', '沒有勇氣拒絕別人'],
    dailyTask: '巡邏，修補壞掉的圍欄。因為健康的界線可以保護心',
    pastVulnerability: '雷雷其實最怕衝突。但正因為如此，他更懂得溫柔地守護界線。',
    companionMessage: '雷雷看起來兇，其實超暖。他拍了拍你的肩膀，說：「你值得被好好對待。」',
  },
  soil: {
    id: 'soil',
    name: '土土',
    emoji: '🌱',
    title: '種子照顧員',
    location: '大地嶺',
    emotionsFocused: ['自我接納', '等待', '耐心'],
    dailyTask: '照顧所有人的種子，每個人來小參室都會得到一顆',
    pastVulnerability: '土土也曾懷疑自己是不是長不出花。現在他知道，每個人都有自己的花期。',
    companionMessage: '土土安靜地蹲在你身邊，用雙手捧著泥土，說：「你會開花的，只是還需要時間。」',
  },
  star: {
    id: 'star',
    name: '星星',
    emoji: '⭐',
    title: '幸福收藏家',
    location: '星光丘',
    emotionsFocused: ['感恩', '快樂', '小確幸'],
    dailyTask: '拿著玻璃瓶收集今天的小幸福，例如陌生人的笑、晚霞、咖啡香、風吹過',
    pastVulnerability: '星星有時候也會忘記幸福。所以他每天都努力收集，提醒自己和別人。',
    companionMessage: '星星開心地跑過來，拿著玻璃瓶說：「今天我收集了你的笑，要放進去嗎？」',
  },
  moon: {
    id: 'moon',
    name: '月月',
    emoji: '🌙',
    title: '夜晚守護者',
    location: '月眠林',
    emotionsFocused: ['焦慮', '失眠', '胡思亂想'],
    dailyTask: '晚上巡夜，拿著鐮刀剪掉那些一直纏住人的念頭。大家叫他剪夢人',
    pastVulnerability: '月月也曾經害怕黑夜。現在他知道，夜晚是讓心休息的地方。',
    companionMessage: '月月安靜地坐在你身邊，點亮一盞暖黃色的燈。他的存在本身就是安心。',
  },
  sunshine: {
    id: 'sunshine',
    name: '暖陽',
    emoji: '☀️',
    title: '曬心人',
    location: '晨曦原',
    emotionsFocused: ['沒有自信', '自我懷疑', '否定自己'],
    dailyTask: '把大家潮濕的心拿去曬曬太陽',
    pastVulnerability: '暖陽永遠笑笑的，不是因為沒有煩惱，而是知道每一天都會過去。',
    companionMessage: '暖陽笑著說：「不用急著發光，溫暖就很好。」他的溫度會慢慢融化你的冰。',
  },
  breeze: {
    id: 'breeze',
    name: '微風',
    emoji: '🌬️',
    title: '改變旅人',
    location: '微風草原',
    emotionsFocused: ['離別', '新開始', '轉變'],
    dailyTask: '把風送到需要的人身邊，例如把花香送去難過的人窗前',
    pastVulnerability: '微風最自由，也最懂得陪伴人們度過改變。改變，是新的開始。',
    companionMessage: '微風輕輕吹過，帶來遠方的花香。他說：「改變會帶你去更好的地方。」',
  },
  elder: {
    id: 'elder',
    name: '長老',
    emoji: '🍂',
    title: '守室人',
    location: 'OK洞',
    emotionsFocused: ['所有人'],
    dailyTask: '什麼都做，也什麼都不急著做。每天坐在門口泡茶、織袈裟、修補自己的衣服',
    pastVulnerability: '長老曾經也是被接住的人。他相信：人不是因為被修好才值得被愛，而是在被愛的過程裡，慢慢修補自己。',
    companionMessage: '長老坐在門口，泡著茶。他看著你，沒有說什麼，但你知道他懂。',
  },
};

export const CHARACTER_IDS = Object.keys(CHARACTERS) as Array<keyof typeof CHARACTERS>;
